### ISSUE TITLE
get_user() is false when customer checks out as guest

### ISSUE THREAD

**Issue by dalepgrant** [tombroucke/otomaties-woocommerce-test-emails#1]
When previewing an email from an order created by a guest customer, [Line 78](https://github.com/tombroucke/otomaties-woocommerce-test-emails/blob/master/otomaties-woocommerce-test-emails.php#L78) throws a fatal error because you cannot `get()` from a bool value. `$user` will be false, because `$order->get_user()` in line 73 returns false for guest users.

Suggested fix: [Line 73](https://github.com/tombroucke/otomaties-woocommerce-test-emails/blob/master/otomaties-woocommerce-test-emails.php#L73):

```patch
- $user       = $order->get_user();
+ $user       = $order->get_user() ?: wp_get_current_user();
```

This provides a fallback to the current logged in user so that at least the code doesn't fallover.

**Comment by tombroucke** [comment]
Fixed in https://github.com/tombroucke/otomaties-woocommerce-test-emails/commit/c8e356565a0186d41a5211bc1f3b32ec21f87644

**Comment by dalepgrant** [comment]
Hero. Thanks for sharing. We had this on our list of plugins to develop to help our builds; yours will save us so much time 🙏
